app:
  Port: 8080
  Name: shelter-apps
  Local: en
  Environment: local
  Key: shelter-apps
  Debug: true
  MigrateKey:
  UploadFolder: upload

database:
  Host: [ 'shelter-apps-db.0kthmmf.mongodb.net']
  Port: [ 27017 ]
  Database: [ 'shelter-apps' ]
  Username: [ 'tomomisooya' ]
  Password: [ 'aAjV3oEE3sQ0qjcn' ]
  ExternalTableName: ['staging_items']

#database:
#  Host: [ '35.240.248.22']
#  Port: [ 27017 ]
#  Database: [ 'shelter-apps' ]
#  Username: [ 'shelter-app' ]
#  Password: [ 'pass123' ]
#  ExternalTableName: ['staging_items']

Proxy:
  ThrustProxy: ['35.240.248.22']

AccessToken:
  Key: secret
  AccessTokenHeaderName: Authorization
  AccessTokenHeaderPrefix: Bearer
  AccessTokenExpireHour : 24
  RefreshTokenExpireHour : 72
  AccessTokenSecret: Bearer
  RefreshTokenSecret: refresh_token_secret
  VerificationTokenExpireHour: 30

Email:
  File: domains/user/mail/pkg
  SenderHost: smtp.gmail.com
  SenderPort: 587
  SenderEmailName: Shelter Apps
  SenderEmailAddress: reagentreagent4@gmail.com
  SenderEmailPassword: dwqwziohlopnfurk
  Attachments: readme.txt
  Type: email

Domain:
  Name: 192.168.43.15
  Protocol: https
  FrontendPath: /email/verification
  Backend:
  Port: 8081

Image:
  Folder: uploads
  PetPath : pets
  UserPath: user
  ShelterPath: shelter
  ProfilePath: profile
  TempPath: temp

Midtrans:
  ServerKey:
  Environment:
