name: Deploy Back-End

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: install the gcloud CLI
        uses: google-github-actions/setup-gcloud@v2.0.0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: build and push docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT }}
        run:
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev
          docker build -t asia-southeast2-docker.pkg.dev/$GCP_PROJECT/docker-artifact/alpine:latest .
          docker push asia-southeast2-docker.pkg.dev/$GCP_PROJECT/docker-artifact/alpine:latest