name: Deploy Back-End

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: shelter-apps
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
  GAR_NAME: ${{ secrets.GAR_NAME }}
  REGION: ${{ secrets.GAR_REGION }}
  PROJECT_ID: ${{ secrets.GAR_PROJECT}}
  CONTAINER_REGISTRY: gcr.io/${{ secrets.GCP_PROJECT }}
  GIT_TAG: v0.1.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [ '1.20' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run:  go version

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_APPLICATION_CREDENTIALS }}

#      - name: Login To Google Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.HUB_USERNAME }}
#          password: ${{ secrets.HUB_PASSWORD }}

      - name: Configure Docker with gcloud
        run: |-
          gcloud auth configure-docker "${{ env.GAR_LOCATION }}-docker.pkg.dev"

      - name: Build Docker image
        run: |-
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{env.IMAGE_NAME}}:${{ github.sha }}" ./
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{env.IMAGE_NAME}}:${{ github.sha }}"
         
      - name: Debug Environment Variables
        run: |
          echo "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"

      - name: Deploy to cloud run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.IMAGE_NAME }}
          region: ${{ env.GAR_LOCATION }}
          image: "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{env.IMAGE_NAME}}:${{ github.sha }}"

      - name: Shout Output
        run: echo ${{ steps.deploy.outputs.url }}